CREATE TABLE Products (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_PRICE DECIMAL(10, 2) NOT NULL,
    PRODUCT_ARTICLE VARCHAR(255),
    PRODUCT_QUANTITY INT NOT NULL,
    DATE_CREATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	IS_HIDDEN BOOLEAN DEFAULT 0
);